#!/bin/sh
exec 2>&1
set -e

# start docker
sv start docker

# check docker is ready
docker info

# set cgroup options
echo -n 1 > /sys/fs/cgroup/memory/memory.use_hierarchy

# create scratch image if it doesn't exist
if ! docker history scratch; then
  python -c 'import sys, tarfile; tarfile.open(fileobj=sys.stdout, mode="w|").close()' | docker import - scratch
fi

# check if weave images exist
if docker history zettio/weave && docker history zettio/weavedns; then
  # weave images exist, tell sv not to restart us
  echo weave images exist
  exec sv down weave-maker
fi

# weave images don't exist, make them
cd "$GOPATH/src/github.com/zettio/weave"
CGO_CPPFLAGS="$CPPFLAGS" CGO_LDFLAGS="$LDFLAGS" make SUDO=
rm -f /var/tmp/weave*.tar
