#!/bin/bash
cmd=poweroff
timeout=7
while getopts hrt: opt
do
  case $opt in
    h)
      cmd=poweroff
      ;;
    r)
      cmd=reboot
      ;;
    t)
      timeout="$OPTARG"
      ;;
  esac
done
shift $((OPTIND-1))

nohup _shutdown "$cmd" "$timeout" >& /dev/null
