#!/bin/sh
if grep -q 'heddle_prepare=1' /proc/cmdline; then
  if [ -c /dev/ttyAMA0 ]; then
    exec > /dev/ttyAMA0 2>&1
  else
    exec > /dev/ttyS0 2>&1
  fi
else
  exec 2>&1
fi
set -e

# check if any prepare_ services are still running
if sv status /service/prepare_* | grep -v '^down.*normally up;'; then
  echo other prepare services are still running
  # we'll be restarted and check for prepare_ services again
  exit 1
fi

# if we're just preparing, poweroff
if grep -q 'heddle_prepare=1' /proc/cmdline; then
  # don't rely on clean shutdown (for fragile software only!)
  # Not all QEMU machines support poweroff so assume -no-reboot was used
  reboot
fi

# tell sv not to restart us
exec sv down prepare
