#!/bin/sh
port="$(grep -oE 'console=tty(S|USB)[0-9]+' /proc/cmdline | head -n 1 | sed 's/console=//')"
if [ -c "/dev/$port" ]; then
  echo "agetty serial: running agetty on port $port"
  exec setsid agetty --nohostname -o '-p -- \u' "$port"
fi
if [ -z "$port" ]; then
  echo "agetty serial: no serial port specified"
else
  echo "agetty serial: not a block device: $port"
fi
exec sv down agetty-serial
