#!/bin/sh
port="$(grep -oE 'console=tty(S|USB)[0-9]+' /proc/cmdline | head -n 1 | sed 's/console=//')"
echo "agetty serial: running agetty on port $port"
if [ -z "$port" ]; then
  exec sv down agetty-serial
else
  exec setsid agetty -o '-p -- \u' "$port"
fi
