#!/bin/sh
if grep -q 'heddle_prepare=1' /proc/cmdline; then
  if [ -c /dev/ttyAMA0 ]; then
    exec > /dev/ttyAMA0 2>&1
  else
    exec > /dev/ttyS0 2>&1
  fi
else
  exec 2>&1
fi
mkdir -p /extra/docker
rm -f /var/run/docker.pid
# set cgroup options
echo -n 1 > /sys/fs/cgroup/memory/memory.use_hierarchy
# run docker
if grep -q 'heddle_prepare=1' /proc/cmdline; then
  export DOCKER_ALLOW_SCRATCH=1
fi
exec unshare -m docker -d -g /extra/docker #--storage-opt dm.override_udev_sync_check=true
