#!/bin/sh
exec 2>&1
mkdir -p /extra/docker /var/lib
ln -sf /extra/docker /var/lib
rm -f /var/run/docker.pid
# set cgroup options
echo -n 1 > /sys/fs/cgroup/memory/memory.use_hierarchy
# run docker
if grep -q 'heddle_prepare=1' /proc/cmdline; then
  export DOCKER_ALLOW_SCRATCH=1
fi
exec docker -d
